name: Deploy Frontend

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: vercel-deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

defaults:
  run:
    working-directory: ./frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_STATSIG_CLIENT_KEY: ${{ secrets.NEXT_PUBLIC_STATSIG_CLIENT_KEY }}
          STATSIG_SERVER_API_KEY: ${{ secrets.STATSIG_SERVER_API_KEY }}
          EXPERIMENTATION_CONFIG_ITEM_KEY: ${{ secrets.EXPERIMENTATION_CONFIG_ITEM_KEY }}

      - name: Deploy to Vercel
        run: npx vercel --token $VERCEL_TOKEN --org $VERCEL_ORG_ID --project $VERCEL_PROJECT_ID --prod
        env:
          NEXT_PUBLIC_STATSIG_CLIENT_KEY: ${{ secrets.NEXT_PUBLIC_STATSIG_CLIENT_KEY }}
          STATSIG_SERVER_API_KEY: ${{ secrets.STATSIG_SERVER_API_KEY }}
          EXPERIMENTATION_CONFIG_ITEM_KEY: ${{ secrets.EXPERIMENTATION_CONFIG_ITEM_KEY }}
