name: Deploy to Vercel

on:
  push:
    branches: [ main, develop, feature/fix-upload-page ]  # Agregar develop para despliegues de desarrollo
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Ejecutar en main (producción), develop (desarrollo) o en ramas feature (preview)
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/feature/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Run linting
      run: |
        cd frontend
        npm run lint

    - name: Run TypeScript check
      run: |
        cd frontend
        npx tsc --noEmit

    - name: Build application
      run: |
        cd frontend
        npm run build

    - name: Check Vercel secrets
      run: |
        if [ -z "$VERCEL_TOKEN" ]; then
          echo "VERCEL_TOKEN is not set"
          exit 1
        fi
        if [ -z "$VERCEL_ORG_ID" ]; then
          echo "VERCEL_ORG_ID is not set"
          exit 1
        fi
        if [ -z "$VERCEL_PROJECT_ID" ]; then
          echo "VERCEL_PROJECT_ID is not set"
          exit 1
        fi
        echo "All Vercel secrets are configured"
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    - name: Deploy to Vercel (Preview)
      if: github.ref != 'refs/heads/main'
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod=false'
        working-directory: ./frontend

    - name: Deploy to Vercel (Production)
      if: github.ref == 'refs/heads/main'
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
        working-directory: ./frontend
